// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpdbjpaatpydeekemqaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZGJqcGFhdHB5ZGVla2VtcWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwMzg2MTUsImV4cCI6MjA4MTYxNDYxNX0.EXClohcfPj3h7L3fWBjAZQL4dwsu5UzClbFyFit_aOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});